# scheduledb
#version: '3.1'
version: '2.0'

services:

  mongo:
    image: tssg-mongo:0.2
    build:
      context: .
      dockerfile: mongo-Dockerfile
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sch3dul3db
    command: --config /etc/mongod.conf

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sch3dul3db

  backend:
    image: tssg-node-backend:${backendVersion}
    build:
        context: .
        dockerfile: backend-Dockerfile
    restart: always        
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      tssgMongoDB_URL: "mongodb://root:sch3dul3db@mongo:27017/tssg-tech?authSource=admin"
      tssgApiURL: backend
    expose:
      - "7010"
    ports:
      - 7010:7010
    command: /bin/bash backend.start
    
  frontend:
    #image: node:lts
    image: tssg-node-frontend:${frontendVersion}
    build:
        context: .
        dockerfile: frontend-Dockerfile
    restart: always        
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - TSSGAPIURL
    expose:
      - "4200"
    ports:
      - 4200:4200
    #command: node_modules/@angular/cli/bin/ng serve
    command: /bin/bash frontend.start
    
volumes:
  mongodb:
