# scheduledb
version: '3.1'

services:

  mongo:
    image: tssg-mongo:0.1
    build:
      context: .
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sch3dul3db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sch3dul3db
    
volumes:
  mongodb: